server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**, /api/test/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
        - id: field-service
          uri: lb://field-service
          predicates:
            - Path=/api/fields/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

halisaha:
  app:
    jwtSecret: ${JWT_SECRET:halisahaSecretKey}
    jwtExpirationMs: ${JWT_EXPIRATION:86400000} 